name: Release

on: 
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build release and report to SonarQube Cloud
        run: mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.organization=vaulttec -Dsonar.projectKey=org.vaulttec.sonarqube.auth.oidc:sonar-auth-oidc-plugin -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release with plugin jar
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/*.jar"
          artifactContentType: application/jar
          token: ${{ secrets.GITHUB_TOKEN }}
